### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by acBool** [Mintegral-official/mintegral_admob_adapter_ios#1]
It can't use ,because it is compile error.
#import <GoogleMobileAds/GADNativeAppInstallAd.h>   what is this file? Admob no the file

**Comment by Mintegral-official** [comment]
hi,sorry,but you may use the old adapter just only for admob below 7.46.0, here we release the new adapter for admob 7.50.0 but just rewardVideo for temp, we will support more ad type soon.
