### ISSUE TITLE
Cocoapods warning

### ISSUE THREAD

**Issue by polmum** [Mintegral-official/mintegral_admob_adapter_ios#2]
Using the latest pod version, we get the following warning:
`[!] Unable to read the license file Fmk/LICENSE.txt for the spec MintegralAdSDK (6.3.5.0)`

We understand this is a minor warning, but it should be easy to fix.

**Comment by red3** [comment]
@polmum this warning had beed fixed on the MintegralAdSDK 6.4.0.0 version.
